apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingressClassName: nginx
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - nginx.seang.shop
      - reactjs.seang.shop
      secretName: nginx-k8s-tls
  rules:
  - host: nginx.seang.shop
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx-svc
            port: 
              number: 80
  - host: reactjs.seang.shop
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: react-svc
            port: 
              number: 80
