# This file defines a ClusterIssuer resource for cert-manager to use Let's Encrypt for issuing TLS certificates.
# ClusterIssuer: talks to Let's Encrypt

# API version for cert-manager resources that manage certificates in Kubernetes but make sure we already 
# Specifies the API version for the cert-manager resources.
apiVersion: cert-manager.io/v1 
kind: ClusterIssuer # Defines a ClusterIssuer resource for issuing certificates cluster-wide
metadata:
  name: letsencrypt-prod # Name of the ClusterIssuer and the secret to store the private key
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: pengseangsim210@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod # Secret to store the private key for this ClusterIssuer
    solvers:
      - http01:
          ingress:
            class: nginx

