apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: path-certificate
spec:
  dnsNames:
    - "path.based.seang.shop"
  secretName: path-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer