apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
  # labels:
  #   app.kubernetes.io/name: myapp
spec:
  containers:
  - name: nginx-container
    image: nginx:alpine
    # resources:
    #   requests:
    #     cpu: "100m"
    #     memory: "128Mi"
    #   limits:
    #     cpu: "250m"
    #     memory: "256Mi"
    ports:
      - containerPort: 80